---

networks:
  johnny: # docker network create -d macvlan --subnet=192.168.0.0/16 --gateway=192.168.0.1 -o macvlan_mode=bridge -o parent=enp1s0 johnny
    external: true
  lagoon: # docker network create --subnet=172.16.0.0/24 lagoon
    external: true

volumes:
  qbittorrent:
  radarr:
  sonarr:
  jackett:

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=984
      - PGID=984
      - TZ=America/Montreal
      - UMASK=022
      - WEBUI_PORT=80
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      # - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=qb
      - TAILSCALE_AUTHKEY=tskey-auth-kaoLUgopP511CNTRL-BUNP6E8Cd6XzL5sHMyNs6XtJAeRSskee
      # - TAILSCALE_FUNNEL=on
    volumes:
      - qbittorrent:/var/lib/tailscale
      - /data/containers/qbittorrent:/config
      - /d/ruby/downloads:/downloads
      - /d/emerald:/emerald
      - /d/ruby:/ruby
      - /d/jade/files/torrents:/torrents
    networks:
      lagoon:
        aliases:
          - "qb"
      johnny:
        ipv4_address: 192.168.1.200
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=984
      - PGID=984
      - TZ=America/Montreal
      - UMASK=022 #optional
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      # - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=radarr
      - TAILSCALE_AUTHKEY=tskey-auth-kaoLUgopP511CNTRL-BUNP6E8Cd6XzL5sHMyNs6XtJAeRSskee
      #- TAILSCALE_FUNNEL=on
    volumes:
      - radarr:/var/lib/tailscale
      - /data/containers/radarr:/config
      - /l/backup/raktar/radarr:/config/backup
      - /d/emerald:/emerald
    networks:
      lagoon:
        aliases:
          - "rdr"
      johnny:
        ipv4_address: 192.168.1.201
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=984
      - PGID=984
      - TZ=America/Montreal
      - UMASK=022 #optional
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      # - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=sonarr
      - TAILSCALE_AUTHKEY=tskey-auth-kaoLUgopP511CNTRL-BUNP6E8Cd6XzL5sHMyNs6XtJAeRSskee
      #- TAILSCALE_FUNNEL=on
    volumes:
      - "sonarr:/var/lib/tailscale"
      - "/data/containers/sonarr:/config"
      - "/l/backup/raktar/sonarr:/config/Backups"
      - "/d/emerald:/emerald"
    networks:
      lagoon:
        aliases:
          - "snr"
      johnny:
        ipv4_address: 192.168.1.202
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
      - AUTO_UPDATE=false #optional
      # - RUN_OPTS=run options here #optional
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      # - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=jackett
      - TAILSCALE_AUTHKEY=tskey-auth-kaoLUgopP511CNTRL-BUNP6E8Cd6XzL5sHMyNs6XtJAeRSskee
      # - TAILSCALE_FUNNEL=on
    volumes:
      - "jackett:/var/lib/tailscale"
      - /data/containers/jackett:/config
      - /d/jade/files/torrents:/torrents
    networks:
      lagoon:
        aliases:
          - "jckt"
      johnny:
        ipv4_address: 192.168.1.203
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Montreal
    networks:
      - lagoon
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland
