---
networks:
  # lagoon:
  #   external: true
  lagoon:
    name: lagoon
    ipam:
      config:
        - subnet: 172.16.0.0/16

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=989
      - PGID=989
      - TZ=America/Montreal
      - UMASK=022
      - WEBUI_PORT=80
    volumes:
      - "/data/containers/qbittorrent:/config"
      - "/d/ruby/downloads:/downloads"
      - "/d/emerald:/emerald"
      - "/d/emerald:/box1"
      - "/d/ruby:/box2"
    networks:
      - lagoon
    ports:
      - 6881:6881
      - 8081:80
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=990
      - PGID=990
      - TZ=America/Montreal
      - UMASK=022 #optional
    volumes:
      - "/data/containers/radarr:/config"
      - "/l/backup/raktar/radarr:/config/backup"
      - "/d/emerald:/emerald"
      - "/d/emerald:/box1"
    networks:
      - lagoon
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=991
      - PGID=991
      - TZ=America/Montreal
      - UMASK=022 #optional
    volumes:
      - "/data/containers/sonarr:/config"
      - "/l/backup/raktar/sonarr:/config/Backups"
      - "/d/emerald:/emerald"
      - "/d/emerald:/box1"
    networks:
      - lagoon
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=988
      - PGID=988
      - TZ=America/Montreal
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=run options here #optional
    volumes:
      - "/data/containers/jackett:/config"
    networks:
      - lagoon
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Montreal
    networks:
      - lagoon
    ports:
      - 8191:8191
    restart: unless-stopped
