version: "2"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Toronto
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /containers/qbittorrent/config:/config
      - /srv/dev-disk-by-label-Slim/slim/files/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    labels:
      - "LABEL com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1002
      - PGID=1000
      - TZ=America/Toronto
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=run options here #optional
    volumes:
      - /containers/jackett/config:/config
    ports:
      - 9117:9117
    labels:
      - "LABEL com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1003
      - PGID=1000
      - TZ=America/Toronto
      - UMASK_SET=022 #optional
    volumes:
      - /containers/radarr/config:/config
      - /srv//dev-disk-by-label-Mauve/mauve/video/movies:/movies
      - /srv//dev-disk-by-label-Slim/slim/files/downloads:/downloads
    ports:
      - 7878:7878
    labels:
      - "LABEL com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1004
      - PGID=1000
      - TZ=America/Toronto
      - UMASK_SET=022 #optional
    volumes:
      - /containers/sonarr/config:/config
      - /srv//dev-disk-by-label-Tangerine/tangerine/video/tvshows:/tv
      - /srv//dev-disk-by-label-Tangerine/tangerine/video/others/documentaries:/videos/documentaries
      - /srv//dev-disk-by-label-Tangerine/tangerine/video/others/miniseries:/videos/miniseries
      - /srv//dev-disk-by-label-Slim/slim/files/downloads:/downloads
    ports:
      - 8989:8989
    labels:
      - "LABEL com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
