---

networks:
  johnny:
    external: true
  lagoon:
    external: true

volumes:
  homeassistant_ts:
  mosquitto:
  nodered_ws: # workspace
  nodered_ts:

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    privileged: true
    environment:
      - PUID=986
      - PGID=986
      - HA_PORT=80
      - TZ=America/Montreal
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      - TAILSCALE_HOSTNAME=homeassistant
      - TAILSCALE_AUTHKEY=tskey-auth-kR276wZd9421CNTRL-7nT2HNWVe3gz6DaFeo9u3g5daBGJKpLN
      - TAILSCALE_FUNNEL=on
    volumes:
      - homeassistant_ts:/var/lib/tailscale
      - /data/containers/appdaemon/apps:/config/appdaemon/apps
      - /l/backup/raktar/homeassistant:/config/backups
      - /data/containers/homeassistant:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      lagoon:
        aliases:
          - "ha"
      johnny:
        ipv4_address: 192.168.2.210
    extra_hosts:
      - "host:192.168.2.192"
    restart: unless-stopped
    labels:
      - falarie.groupby=iot

  mosquitto:
    image: docker.io/eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - mosquitto:/mosquitto/data
      - /data/containers/mosquitto/config:/mosquitto/config
      - /data/containers/mosquitto/log:/mosquitto/log
    networks:
      lagoon:
        aliases:
          - "msqt"
      johnny:
        ipv4_address: 192.168.2.211
    restart: unless-stopped
    labels:
      - falarie.groupby=iot

  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: appdaemon
    depends_on: [homeassistant, mosquitto]
    user: 986:986
    environment:
      - HA_URL=http://localhost:80
      - TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzMzMyM2Y5NGMyMjg0MzlhYmZkZGNhYzNkOTJmYWEwMiIsImlhdCI6MTczNTY5OTkxNSwiZXhwIjoyMDUxMDU5OTE1fQ.IbQOoigaz9q2UvnSZvmOKUUpO71WycXhrRpZaywLzfQ
      - DASH_URL=http://homeassistant.iot:5050
    volumes:
      - /data/containers/appdaemon:/conf
      - ./appdaemon/appdaemon.yaml:/conf/appdaemon.yaml
      - ./appdaemon/secrets.yaml:/conf/secrets.yaml
    network_mode: service:homeassistant
    restart: unless-stopped
    labels:
      - falarie.groupby=iot

  ts_nodered:
    image: tailscale/tailscale
    container_name: ts_nodered
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TZ=America/Montreal
      - TS_HOSTNAME=nodered
      - TS_AUTHKEY=tskey-auth-kR276wZd9421CNTRL-7nT2HNWVe3gz6DaFeo9u3g5daBGJKpLN
      - TS_EXTRA_ARGS=--accept-dns=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - nodered_ts:/var/lib/tailscale
      - ./ts_nodered:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      lagoon:
        aliases:
          - nr
      johnny:
        ipv4_address: 192.168.2.212
    extra_hosts:
      - "host:192.168.2.192"
    restart: unless-stopped
    labels:
      - falarie.groupby=iot

  nodered:
    image: nodered/node-red
    container_name: nodered
    depends_on: [ts_nodered]
    user: 1000:100
    healthcheck:
      test: curl -f http://127.0.0.1 || exit 1
      interval: 5m
      retries: 3
    env_file:
      - ~/secrets/nodered.env
    environment:
      - NODE_RED_HTTPADMINROOT=/admin
      - NODE_RED_PORT=80
      - TZ=America/Montreal
    volumes:
      - ./nodered/settings.js:/data/settings.js
      - /data/containers/nodered/data:/data
      - /data/containers/nodered/projects:/data/projects
      - nodered_ws:/workspace
      - /d/ruby/audio/podcasts/:/podcasts
    network_mode: service:ts_nodered
    restart: unless-stopped
    labels:
      - falarie.groupby=iot
