---

networks:
  johnny:
    external: true
  lagoon:
    external: true

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    environment:
      - PUID=986
      - PGID=986
      - HA_PORT=80
      - TZ=America/Montreal
    volumes:
      - /data/containers/homeassistant:/config
    networks:
      lagoon:
      johnny:
        ipv4_address: 192.168.1.7
    restart: unless-stopped
    labels:
      - falarie.groupby=iot
