---
networks:
  lagoon:
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    hostname: heimdall
    container_name: heimdall
    environment:
      - PUID=986
      - PGID=986
      - TZ=America/Montreal
    volumes:
      - /data/containers/heimdall/config:/config
    networks:
      - lagoon
    ports:
      - 9080:80
      - 9443:443
    restart: unless-stopped
