---

networks:
  johnny:
    external: true
  lagoon:
    external: true

services:
  mosquitto:
    image: docker.io/eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /data/containers/mosquitto/data:/mosquitto/data
      - /data/containers/mosquitto/config:/mosquitto/config
      - /data/containers/mosquitto/log:/mosquitto/log
    networks:
      lagoon:
      johnny:
        ipv4_address: 192.168.1.8
    restart: unless-stopped
    labels:
      - falarie.groupby=iot
