---

networks:
  johnny:
    external: true

  lagoon:
    external: true

volumes:
  mosquitto_data:
    name: mosquitto_data

services:
  mosquitto:
    image: docker.io/eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - mosquitto_data:/mosquitto/data
      - /data/containers/mosquitto/config:/mosquitto/config
      - /data/containers/mosquitto/log:/mosquitto/log
    networks:
      lagoon:
      johnny:
        ipv4_address: 192.168.1.212
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    restart: unless-stopped
    labels:
      - fstemarie.groupby=iot
