---

networks:
  johnny:
    external: true
  lagoon:
    external: true

volumes:
  airsonic:

services:
  ts_airsonic:
    image: tailscale/tailscale:latest
    container_name: ts_airsonic
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TZ=America/Montreal
      - TS_HOSTNAME=airsonic
      - TS_AUTHKEY=tskey-auth-kKoZMEUiEW11CNTRL-zfYCrHYF5wUoHJ3Ve3YsvUZi2bVN4nMM4
      # - TS_EXTRA_ARGS=
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - airsonic:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./serve:/config
    networks:
      lagoon:
      johnny:
        ipv4_address: 192.168.1.204
    restart: unless-stopped
    labels:
      - falarie.groupby=airsonic

  airsonic:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic
    environment:
      - PUID=984
      - PGID=984
      - TZ=America/Montreal
      - "JAVA_OPTS=-Dserver.port=80"
      # - CONTEXT_PATH=/airsonic
    volumes:
      - /data/containers/airsonic:/config
      - /d/ruby/audio:/audio
      - /d/ruby/audio/playlists:/playlists
    network_mode: service:ts_airsonic
    # ports:
    #   - 4040:4040
    #   - 4041:4041
    restart: unless-stopped
    labels:
      - falarie.groupby=airsonic
