---

networks:
  lagoon:
    external: true

services:
  airsonic:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic
    environment:
      - PUID=985
      - PGID=985
      - TZ=America/Montreal
      # - "JAVA_OPTS=-Dserver.port=80"
      # - CONTEXT_PATH=/airsonic
    volumes:
      - /data/containers/airsonic:/config
      - /d/ruby/audio:/audio
      - /d/ruby/audio/playlists:/playlists
    networks: [lagoon]
    ports:
      - 4040:4040
    #   - 4041:4041
    restart: unless-stopped
