---

networks:
  johnny:
    external: true

  lagoon:
    external: true

services:
  airsonic:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic
    environment:
      - PUID=984
      - PGID=984
      - TZ=America/Montreal
      - "JAVA_OPTS=-Dserver.port=80"
      # - CONTEXT_PATH=/airsonic
    volumes:
      - /data/containers/airsonic:/config
      - /d/ruby/audio:/audio
      - /d/ruby/audio/playlists:/playlists
    networks:
      lagoon:
      johnny:
        ipv4_address: 192.168.1.204
    # ports:
    #   - 4040:4040
    #   - 4041:4041
    restart: unless-stopped
