---

networks:
  johnny:
    external: true
  lagoon:
    external: true

services:
  netboot:
    image: lscr.io/linuxserver/netbootxyz
    container_name: netboot
    user: 1000:100
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
      # - MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - /data/containers/netboox.xyz/config:/config
      - /data/containers/netboox.xyz/assets:/assets
    networks:
      lagoon:
      johnny:
    # ports:
    #   - 3000:3000
    #   - 69:69/udp
    #   - 8080:80 #optional
    restart: unless-stopped