---
networks:
  lagoon:
    external: true

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      TZ: America/Montreal
    volumes:
      - /data/containers/homarr/config:/app/data/configs
      - /data/containers/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lagoon
    ports:
      - 7575:7575
    restart: unless-stopped
