---

networks:
  lagoon:
    external: true

services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    env_file:
      - ~/secrets/mariadb.env
    environment:
      - PUID=990
      - PGID=990
      - TZ=America/Montreal
      # - MYSQL_ROOT_PASSWORD=
      # - MYSQL_DATABASE=USER_DB_NAME #optional
      # - MYSQL_USER=MYSQL_USER #optional
      # - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /data/containers/mariadb:/config
    networks: [lagoon]
    ports:
      - 3306:3306
    restart: unless-stopped

  phpmyadmin:
    image: ghcr.io/linuxserver/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - ~/secrets/phpmyadmin.env
    environment:
      - TZ=America/Montreal
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      # - PMA_ARBITRARY=1
      # - PMA_USER=
      # - PMA_PASSWORD=
    volumes:
      - /data/containers/phpmyadmin/config:/config
    networks: [lagoon]
    ports:
      - 8080:80
    depends_on: [mariadb]
    restart: unless-stopped
