version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower2
    environment:
      - WATCHTOWER_LABEL_ENABLE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
