---
version: "2.1"
services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=984
      - PGID=984
      - TZ=America/Montreal
      - RUN_OPTS= #optional
    volumes:
      - /data/containers/tvheadend:/config
      - /d/emerald/video/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/dvb:/dev/dvb #optional
    restart: unless-stopped