---

services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: tailscale
    environment:
      - TS_HOSTNAME=raktar
      - TS_AUTHKEY=tskey-auth-kwAD4x6CNTRL-5WTyP4gUB8TxQqpwFjYy7TaS9qHNPuQsi
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      - TS_ROUTES=192.168.1.0/24
      - TS_EXTRA_ARGS=--accept-routes --ssh
      - TZ=America/Montreal
    volumes:
      - "/var/lib:/var/lib"
      - "/dev/net/tun:/dev/net/tun"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
