---

networks:
  johnny:
    external: true

  lagoon:
    external: true

services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    env_file:
      - ~/secrets/mariadb.env
    environment:
      - PUID=990
      - PGID=990
      - TZ=America/Montreal
      # - MYSQL_ROOT_PASSWORD=
      # - MYSQL_DATABASE=USER_DB_NAME #optional
      # - MYSQL_USER=MYSQL_USER #optional
      # - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /data/containers/mariadb:/config
    networks:
      lagoon:
      johnny:
        ipv4_address: 192.168.1.212
    ports:
      - 3306:3306
    restart: unless-stopped
    labels:
      - fstemarie.groupby=database
