---

networks:
  lagoon:
    external: true
  johnny:
    external: true

services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    volumes:
      - /data/containers/viseron:/config
      - /d/jade/recordings:/recordings
    networks:
      lagoon:
      johnny:
        ipv4_address: 192.168.1.213
    # ports:
    #   - 8888:8888
    environment:
      # - PUID=1000
      # - PGID=100
      - TZ=America/Montreal
    restart: unless-stopped
    labels:
      - falarie.groupby=iot