---

services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: tools_wireshark
    hostname: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
    volumes:
      - /data/containers/wireshark:/config
    ports:
      - 3000:3000 #optional
      - 3001:3001 #optional
    restart: no
